w01/diary/urls.py
from django.urls import path,include
from . import views

app_name = "diary"
urlpatterns = [
    path('diaryHome/', views.diaryHome, name="diaryHome"),
    path('MdiaryList/', views.MdiaryList, name="MdiaryList"),
    path('diaryWrite/', views.diaryWrite, name="diaryWrite"),
    path('diaryMake/', views.diaryMake, name="diaryMake"),
    path('diary_view/<int:cno>/', views.diary_view, name="diary_view"),
    path('dmodify/<int:cno>/', views.dmodify, name='dmodify'),  # 글 수정
    path('CdiaryList/', views.CdiaryList, name="CdiaryList"), # 생성한 다이어리 리스트
    path('JdiaryList/', views.JdiaryList, name="JdiaryList") # 생성한 다이어리 리스트
]

w01/w01/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin1/', include('admin1.urls')),
    path('loginpage/', include('loginpage.urls')),
    path('customer/', include('customer.urls')),
    path('emotion/', include('emotion.urls')),
    path('', include('home.urls')),
    path('main/', include('home.urls')),
    path('diary/', include('diary.urls')),
    path('mypage/', include('mypage.urls')),
    path('comment/', include('comment.urls')),
    path('calendar1/', include('calendar1.urls')),
    path('family1/', include('family1.urls')),
]


# settings.py 안에
# MEDIA_URL = 'media/' 로 들어오면
# MEDIA_ROOT = os.path.join(BASE_DIR,'media') 에서 찾아라
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin1/', include('admin1.urls')),
    path('loginpage/', include('loginpage.urls')),
    path('customer/', include('customer.urls')),
    path('emotion/', include('emotion.urls')),
    path('', include('home.urls')),
    path('main/', include('home.urls')),
    path('diary/', include('diary.urls')),
    path('mypage/', include('mypage.urls')),
    path('comment/', include('comment.urls')),
    path('calendar1/', include('calendar1.urls')),
    path('family1/', include('family1.urls')),
]


# settings.py 안에
# MEDIA_URL = 'media/' 로 들어오면
# MEDIA_ROOT = os.path.join(BASE_DIR,'media') 에서 찾아라
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

w01/diary/models.py
from django.db import models
from loginpage.models import Member
from django.core.exceptions import ValidationError

# 개인 다이어리 테이블
class MdiaryBoard(models.Model):
  mno = models.AutoField(primary_key=True)
  id = models.ForeignKey(Member,on_delete=models.DO_NOTHING, null=True)
  mtitle = models.CharField(max_length=1000,default='나의 일기장')
  mdate = models.DateField(auto_now=True)

  def __str__(self):
    return f"{self.mno},{self.id.id},{self.id.nicName},{self.mtitle},{self.mdate}"
  

# 우체통
from loginpage.models import Member
class Letter(models.Model):
  lno = models.AutoField(primary_key=True)
  member = models.ForeignKey(Member,on_delete=models.DO_NOTHING, null=True)
  ltitle = models.CharField(max_length=1000)
  lcontent = models.TextField()
  ldate = models.DateTimeField(auto_now=True)
  lhit = models.IntegerField(default=0)

  def __str__(self):
    return f"{self.lno},{self.member},{self.ltitle},{self.lcontent},{self.ldate}"
  

# 그룹 다이어리 db 나중에 그룹 다이어리 생성 시 중복 체크해서 raise ValidationError("이미 그룹 다이어리가 존재합니다.")
# 한 아이디가 하나의 그룹 다이어리 생성 할 수 있도록
class GroupDiary(models.Model):
  gno = models.IntegerField(default=0, null=False)
  member = models.ForeignKey(Member,on_delete=models.DO_NOTHING, null=False)
  gtitle = models.CharField(max_length=200)
  gName = models.CharField(max_length=100, null=False, default="우리 가족") # 그룹이름
  created_at = models.DateTimeField(auto_now_add=True)
  role = models.IntegerField(default=1)
  
  def __str__(self):
    return f"{self.gno},{self.member.id},{self.gtitle},{self.gName},{self.created_at}"

  # def clean(self):
  #   # 같은 사용자가 이미 그룹 다이어리를 생성한 경우 ValidationError 발생
  #   if GroupDiary.objects.filter(member=self.member).exists():
  #       raise ValidationError("이미 그룹 다이어리가 존재합니다.")
    

# 다이어리 작성 -> 내용 db
from django.utils import timezone
class Content(models.Model):
  cno = models.AutoField(primary_key=True)
  member = models.ForeignKey(Member,on_delete=models.DO_NOTHING, null=False) # 유저id & 닉네임 가져옴
  ctitle = models.CharField(max_length=1000)
  ccontent = models.TextField(null=True)
  cdate = models.DateTimeField(default=timezone.now)  # 기본값을 오늘 날짜로 설정
  group_diary  = models.ManyToManyField(GroupDiary, blank=True)
  # 공용다이어리 db 만들면 추후 업데이트
  image = models.ImageField(upload_to='diary_images/', blank=True, null=True)  # 이미지

   # 개인다이어리 db
  mdiary = models.ForeignKey(MdiaryBoard, on_delete=models.CASCADE, null=True, blank=True)
  def __str__(self):
    group_diaries = ", ".join([str(diary) for diary in self.group_diary.all()])
    return f"{self.cno}, {self.member.id}, {self.ctitle}, {self.ccontent}, {self.cdate}, [{group_diaries}], {self.member.nicName}"

w01/diary/views.py
from django.shortcuts import render, redirect
from loginpage.models import Member
from diary.models import Letter
from django.utils import timezone
from diary.models import Content
from diary.models import GroupDiary
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.db.models import Max
from django.db.models import Q



# 우체통
from .models import MdiaryBoard

## 다이어리 HOME
def diaryHome(request):
	id = request.session.get('session_id')
	name = request.session.get('session_name')
	qs_group = GroupDiary.objects.filter(member=id)

	## 공유 일기장
	# 1. 유저가 생성공유일기장

	qs_createdDiary = GroupDiary.objects.filter(Q(member__id=id) & Q(role=1))
	c_context = {} #변수

	if qs_createdDiary:
		# 초대멤버가져오기
		qs_joinedMem = GroupDiary.objects.filter(gno=qs_createdDiary[0].gno, role=2)
		if qs_joinedMem:
			c_context = {"creator":qs_createdDiary[0], "user_name":name, "joined_members":qs_joinedMem}
			print("있음",c_context)
		else:
			c_context = {"creator":qs_createdDiary[0], "user_name":name,}
			print("없음",c_context)
	

	# 2. 유저가 가입한 공유일기장
	qs_joinedDiary = GroupDiary.objects.filter(Q(member__id=id) & Q(role=2))
	if qs_joinedDiary:
		# 멤버 정보가져오기
		# 방장
		gno = qs_joinedDiary[0].gno
		qs_cMem = Member.objects.filter(created_group__gno=gno).first()

		jmems = []
		for jmem in qs_joinedDiary:
			member = jmem.member
			j = Member.objects.get(id=member.id)
			jmems.append(j.name)
		c_context['cMem'] = qs_cMem
		c_context['join_d'] = list(qs_joinedDiary)
		c_context['joined_names'] = jmems


	## 개인 다이어리
	qs_pDiary = MdiaryBoard.objects.get(id=id)
	c_context['pDiary'] = qs_pDiary


	c_context['group'] = qs_group
	print("c_context : ",c_context)
	return render(request,'diaryHome.html',c_context)




	# 우체통
	qs = Letter.objects.all().order_by("ldate")
	member = Member.objects.filter(id=id)
	# personal_diaries = MdiaryBoard.objects.select_related('id').all() # 개인 다이어리 데이터 가져오기
	if member:
		user_nic = member[0].nicName
		context = {"list":qs ,'user_nic':user_nic}
		return render(request,'diaryHome.html',context)
	else:
		context = {'list':qs}
		return render(request,'diaryHome.html',context)
	
		



## 가족다이어리 생성
def diaryMake(request):
	if request.method == 'GET':
		qs_Member = Member.objects.all()
		id = request.session['session_id']
		qs_createdDiary = GroupDiary.objects.filter(Q(member__id=id) & Q(role=1))
		if qs_createdDiary:
			context = {"gmsg":"0"}
			return render(request,'diaryHome.html', context)
		else:
			context = {'members':qs_Member,"gmsg":"1"}
			return render(request,'diaryMake.html', context)

	else:

		id = request.session['session_id']
		member = Member.objects.get(id=id)
		gtitle = request.POST.get('gtitle')
		gName = request.POST.get('gName')
		created_at = request.POST.get('created_at','')
		search_members = request.POST.getlist('search_members[]')
		
		# GroupDiary에 방장 저장
		qs_creator = GroupDiary.objects.create(gtitle=gtitle, gName=gName, created_at=created_at, member=member)
		no = GroupDiary.objects.aggregate(max_gno = Max('gno'))
		qs_creator.gno = no['max_gno']+1
		qs_creator.role = 1
		qs_creator.save()
		
		# Member에 created_group에 방장 저장
		qs_cMem = Member.objects.get(id=id)
		qs_cMem.created_group = qs_creator
		qs_cMem.save()

		# 초대 멤버 저장
		for sMem in search_members:
			# GroupDiary에 멤버 저장
			gno = qs_creator.gno
			role = 2
			qs_sMem = Member.objects.get(id=sMem)
			qs_joinedMem = GroupDiary.objects.create(gno=gno, gtitle=gtitle, gName=gName, created_at=created_at, member=qs_sMem, role=role)

			# Member에 joined_group에 멤버 저장
			qs_sMem.joined_group = qs_joinedMem
			qs_sMem.save()
		
		context = {"gmsg":"1"}

		return render(request, 'diaryHome.html', context)
		




## 내 다이어리 목록
# def MdiaryList(request):
#   qs = Content.objects.all().order_by("-cdate")
#   context = {'content':qs}  
#   return render(request,'MdiaryList.html', context)


## 내 다이어리 목록
from django.contrib.auth.decorators import login_required

@login_required
def MdiaryList(request):
		if request.method == "GET":        
				# 세션에 저장된 ID 가져오기
				session_id = request.session.get('session_id')  # 세션에서 'session_id'를 가져옴
				print("세션아이디:", session_id)

				# 세션에 해당하는 ID가 존재하는지 확인
				if not session_id:
						return render(request, 'error.html', {'message': '세션 ID가 존재하지 않습니다.'})
				
				# session_id를 기준으로 Member 찾기
				member = Member.objects.filter(id=session_id).first()

				# member가 없으면 에러 처리
				if not member:
						return render(request, 'error.html', {'message': '사용자 정보가 존재하지 않습니다.'})

				# MdiaryBoard와 Content 가져오기
				mdiary = MdiaryBoard.objects.filter(id=member).first()  # 사용자와 연결된 MdiaryBoard
				if not mdiary:
					return render(request, 'error.html', {'message': '다이어리 정보가 없습니다.'})

				# 해당 멤버의 Content 가져오기
				qs = Content.objects.filter(member=member).select_related('mdiary').order_by("-cdate")

				npage = request.GET.get('npage', 1)
				paginator = Paginator(qs, 10)
				page_obj = paginator.get_page(npage)
				
				context = {'content': page_obj.object_list,'MdiaryList':page_obj,'mdiary':mdiary}
				return render(request, 'MdiaryList.html', context)
		
		# npage = int(request.GET.get('npage',1))  # 넘어온 현재페이지
		# qs = Content.objects.all().order_by("-cno")
		# # 하단페이지 처리(넘버링)
		# paginator = Paginator(qs,10)  # 10개로 분할
		# mlist = paginator.get_page(npage)  # 1페이지 10개
		# context = {"MdiaryList":mlist, "npage":npage}
		# return render(request,'MdiaryList.html',context)

# 개인 다이어리 제목 수정
from django.http import JsonResponse
from django.shortcuts import get_object_or_404

def update_diary_title(request):
    if request.method == 'POST' and request.is_ajax():
        new_title = request.POST.get('title')
        mdiary = get_object_or_404(MdiaryBoard, id=request.user.id)  # 로그인된 사용자에 맞는 다이어리 가져오기
        mdiary.mtitle = new_title
        mdiary.save()
        return JsonResponse({'success': True})
    return JsonResponse({'success': False})





# 다이어리 작성 저장
def diaryWrite(request):
    if request.method == "GET":
        # 세션에서 사용자 ID 가져오기
        id = request.session.get('session_id')  # 현재 사용자의 ID 가져오기
        current_date = timezone.now().date().strftime('%Y-%m-%d')
        # 생성한 그룹과 참여한 그룹 가져오기
        user = Member.objects.filter(id=id)
        created_group = user[0].created_group
        joined_group = user[0].joined_group
        return render(request, 'diaryWrite.html', {
            'current_date': current_date,
            'created_group': created_group,
            'joined_group': joined_group,
        })
    elif request.method == "POST":
        current_date = timezone.now().date().strftime('%Y-%m-%d')
        # 세션에서 사용자 ID 가져오기
        id = request.session.get('session_id')  # 세션에서 사용자 ID 가져오기
        if not id:
            return HttpResponse("로그인 정보가 없습니다.", status=400)
        # Member 모델에서 해당 ID로 회원 조회
        member = Member.objects.filter(id=id).first()  # 없으면 None 반환
        if not member:
            return HttpResponse("사용자 정보가 존재하지 않습니다.", status=400)
        # 다이어리 작성 내용 저장
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        diary_idc = request.POST.get('diary_idc','')
        diary_idj = request.POST.get('diary_idj','')
        selected_groups = [diary_idc,diary_idj]
        date = request.POST.get('date')
        if date != current_date:
          cdate = date
        else:
          cdate = timezone.now()
        # 로그인 후 첫 접속 시 세션에 diary_count 초기화 (새로운 세션 시작)
        if f"diary_count_{id}" not in request.session:
            request.session[f"diary_count_{id}"] = 1
        else:
            # 세션에 diary_count가 있으면 증가
            diary_count = request.session[f"diary_count_{id}"] + 1
            request.session[f"diary_count_{id}"] = diary_count
        # cno는 세션 고유 번호로 관리된 카운터 값 사용
        cno = str(request.session[f"diary_count_{id}"])
        # Content 객체 생성하여 저장
        new_diary = Content(
            cno=cno, #생성된 cno사용
            member=member,
            ctitle=title,
            ccontent=content,
            image=image,
            cdate=cdate,
        )
        new_diary.save()
        ## 공유하려는 다이어리가 있으면
        if selected_groups[0]  ==  '' and  selected_groups[1]  == '':
          return redirect('diary:MdiaryList')
        else:
            # join된 일기장에만 공유
            if selected_groups[0] == '':
                joined_group = GroupDiary.objects.filter(gno=selected_groups[1]).first()
                new_diary.group_diary.add(joined_group)
            # create 한 일기장에만 공유
            elif selected_groups[1] == '':
                created_group = GroupDiary.objects.filter(gno=selected_groups[0]).first()
                new_diary.group_diary.add(created_group)
            # 모두 공유
            else:
                created_group = GroupDiary.objects.filter(gno=selected_groups[0]).first()
                joined_group = GroupDiary.objects.filter(gno=selected_groups[1]).first()
                new_diary.group_diary.add(created_group,joined_group)
            return redirect('diary:MdiaryList')  # 다이어리 리스트로 리다이렉트


# 다이어리 view 추후 업데이트 >>
def diary_view(request,cno):
		# mdiary = Content.objects.filter(cno=cno)
		
		current_post = Content.objects.filter(cno=cno)
		if not current_post:
				return HttpResponse("게시물이 존재하지 않습니다.", status=404)

		# 이전글: 현재 글보다 cno가 작은 값 중에서 가장 최신 1개
		previous_post = Content.objects.filter(cno__lt=cno).order_by('-cno').first()

		# 다음글: 현재 글보다 cno가 큰 값 중에서 가장 오래된 1개
		next_post = Content.objects.filter(cno__gt=cno).order_by('cno').first()

		# 현재 페이지 번호 가져오기
		pageNum = int(request.GET.get('pageNum', 1))

		session_id = request.session.get('session_id')
		member = Member.objects.filter(id=session_id).first()
		mdiary = MdiaryBoard.objects.filter(id=member).first()

		context = {
				'cont': current_post[0],
				'previous_post': previous_post,  # 이전글 1개
				'next_post': next_post,          # 다음글 1개
				'pageNum': pageNum,
				'mdiary':mdiary
		}
		return render(request,'diary_view.html',context,)

## 글수정페이지, 글수정 저장

w01/diary/templates/diaryWrite.html
{%load static%}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/diary/diary_write.css'%}">
  <link rel="stylesheet" href="{% static 'css/home/main.css'%}">
  <link rel="stylesheet" as="style" crossorigin
    href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css" />
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <title>다이어리 작성</title>
</head>
<!-- 공통 상단좌측메뉴 -->
<script>
  $(function () {
    // GNB 클릭
    $('#menu ul li').on('click', function () {
      $('#menu ul li').removeClass('active');
      $(this).addClass('active');
    });
  });
</script>
</head>
<body>
  <!-- 최상단 메뉴 -->
  <div id="top_nav">
    <h1><a href="#"></a></h1>
    <ul class="top_menu">
      <li><a href="#"><img src="/static/images/home/search_icon.png" alt=""></a></li>
      <li><a href="#"><img src="/static/images/home/bell_off_icon.png" alt=""></a></li>
      <li><a href="#">마이페이지</a></li>
    </ul>
  </div>
  <!-- 좌측 gnb -->
  <div id="gnb">
    <!-- 프로필 -->
    <div id="user_profile">
      <div id="pimg">
        <img src="/static/images/home/default_profile.png" alt="">
      </div>
      <p id="uName">김용준</p>
      <p id="uEmail">kyjoon0105@gmail.com</p>
    </div>
    <!-- Nav -->
    <nav id="menu">
      <ul>
        <a href="#">
          <li class="menu_item">우리 가족 이야기</li>
        </a>
        <a href="#">
          <li class="menu_item active">다이어리</li>
        </a>
        <a href="#">
          <li class="menu_item">감정 돌아보기</li>
        </a>
        <a href="#">
          <li class="menu_item">우리가족</li>
        </a>
        <a href="#">
          <li class="menu_item">캘린더</li>
        </a>
        <a href="#">
          <li class="menu_item">알려드려요</li>
        </a>
      </ul>
    </nav>
    <!-- logout -->
    <div id="logout">
      <a href="#"><span>로그아웃</span></a>
    </div>
  </div>
  <!-- 공통 상단좌측메뉴 -->
  <!-- 다이어리 작성 메인 -->
  <div id="diary_write">
    <h1>일기 작성</h1>
    <form action= "{% url 'diary:diaryWrite' %}" id="writeFrm" name="writeFrm" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <label for="title">제목</label>
        <input type="text" name="title" id="title" placeholder="제목을 입력해주세요." required>
      </div>
      <div class="form-group">
        <!-- 생성 날짜 자동 기입(db) -->
        <label for="date">오늘 날짜</label>
        <input type="date" name="date" id="date" value="{{ current_date }}">
      </div>
      <!-- 사진 업로드 -->
      <div class="form-group">
        <label for="image">사진 업로드</label>
        <div class="file-input-container">
          <input type="file" id="image" name="image" multiple accept="image/*" onchange="previewImages(event)">
        </div>
        <!-- 이미지 미리보기 영역 -->
        <div class="image-preview-container" id="image-preview-container"></div>
      </div>
      <div class="form-group">
        <label for="content">내용</label>
        <textarea name="content" id="content" rows="10" oninput="autoResize(this)" placeholder="내용을 입력해주세요."
          required></textarea>
      </div>
      <!-- 다이어리 체크박스 예시 -->
      <!-- {% if diaries %}
      <div>
        <p>공유 다이어리에 등록합니다:</p>
        {% for diary in diaries %}
        <label>
          <input type="checkbox" name="diary_ids" value="{{ diary.id }}">
          {{ diary.title }}
        </label><br>
        {% endfor %}
      </div>
      {% else %}
      <p>공유 가능한 다이어리가 없습니다.</p>
      {% endif %} -->
      {% if created_group or joined_group %}
      <div class="form-group">
          <label>공유</label><br>
          {% if created_group %}
          <label id="fdiary">
              {{ created_group.gName }}
              <input type="checkbox" id="share" name="diary_idc" value="{{ created_group.gno }}">
          </label>
          {% endif %}
          {% if joined_group %}
          <label id="fdiary">
              {{ joined_group.gName }}
              <input type="checkbox" id="share" name="diary_idj" value="{{ joined_group.gno }}">
          </label>
          {% endif %}
      </div>
      {% endif %}
      <button type="submit" onclick='saveBtn(event)' class="save">저장</button>
      <button type="button" class="cancel" onclick="confirmCancel()">취소</button>
  </div>
  </form>
  <!-- 확대된 이미지 팝업 -->
  <div class="image-popup" id="image-popup">
    <span class="close-popup" onclick="closePopup()">×</span>
    <img id="popup-image" src="" alt="Enlarged Image">
  </div>
</div>
<script type="text/javascript">
  {% comment %} var checkUnload = true;
    $(window).on('beforeunload', function () {
        if (checkUnload) return "이 페이지를 벗어나면 작성된 내용은 저장되지 않습니다.";
    });
    $("#write").on("click", function () {
        checkUnload = false;
        $("submit").submit();
    }); {% endcomment %}
  // 다이어리 저장 후 알림 처리 및 페이지 이동
  function saveBtn(event) {
    event.preventDefault();  // 폼이 자동으로 제출되는 것을 방지
    if ($("#title").val().length < 1) {
      alert("제목을 입력해주세요.");
      $("#title").focus();
      return false;
    }
    writeFrm.submit()
  }
  // 취소 버튼 클릭 시 확인 메시지
  function confirmCancel() {
    var confirmAction = confirm("정말 취소하시겠습니까?");
    if (confirmAction) {
      window.location.href = '/diary/MdiaryList/';  // 취소 후 이동
    }
  }
  if ("{{wmsg}}" == "1"){
    alert("저장되었습니다.")
    location.href = '/diary/MdiaryList/'
  }
  function autoResize(textarea) {
    textarea.style.height = 'auto';
    textarea.style.height = textarea.scrollHeight + 'px';
  }
  // 이미지 미리보기 및 여러 이미지 처리
  function previewImages(event) {
    const files = event.target.files;  // 업로드된 파일 목록
    const previewContainer = document.getElementById('image-preview-container');
    // 기존 이미지가 있다면 유지하고 새로운 이미지를 추가
    Array.from(files).forEach(file => {
      const reader = new FileReader();
      reader.onload = function (e) {
        const img = document.createElement('img');
        img.src = e.target.result;  // 이미지 데이터를 URL로 설정
        img.onclick = function () {
          openPopup(img.src);  // 이미지 클릭 시 확대 보기
        };
        previewContainer.appendChild(img);  // 이미지 미리보기 영역에 추가
      };
      reader.onerror = function (error) {
        console.error("파일 읽기 오류:", error);
      };
      reader.readAsDataURL(file);  // 파일을 데이터 URL로 읽어 이미지 미리보기
    });
  }
  // 이미지 확대 보기 팝업 열기
  function openPopup(imageSrc) {
    const popup = document.getElementById('image-popup');
    const popupImage = document.getElementById('popup-image');
    popup.style.display = 'flex';
    popupImage.src = imageSrc;
  }
  // 이미지 확대 보기 팝업 닫기
  function closePopup() {
    const popup = document.getElementById('image-popup');
    popup.style.display = 'none';
  }
  //이미지 삭제
  function previewImages(event) {
    const files = event.target.files; // 업로드된 파일 목록
    const previewContainer = document.getElementById('image-preview-container');
    Array.from(files).forEach(file => {
      const reader = new FileReader();
      reader.onload = function (e) {
        // 이미지와 삭제 버튼을 감싸는 wrapper 생성
        const wrapper = document.createElement('div');
        wrapper.classList.add('image-wrapper');
        wrapper.style.position = 'relative';
        wrapper.style.display = 'inline-block';
        // 이미지 생성
        const img = document.createElement('img');
        img.src = e.target.result; // 이미지 데이터를 URL로 설정
        img.alt = 'Uploaded image';
        img.onclick = function () {
          openPopup(img.src); // 이미지 클릭 시 확대 보기
        };
        // 삭제 버튼 생성
        const deleteButton = document.createElement('button');
        deleteButton.classList.add('delete-button');
        deleteButton.innerText = '×';
        deleteButton.onclick = function () {
          wrapper.remove(); // 이미지 wrapper 삭제
        };
        // wrapper에 이미지와 버튼 추가
        wrapper.appendChild(img);
        wrapper.appendChild(deleteButton);
        // 미리보기 컨테이너에 wrapper 추가
        previewContainer.appendChild(wrapper);
      };
      reader.onerror = function (error) {
        console.error("파일 읽기 오류:", error);
      };
      reader.readAsDataURL(file); // 파일을 데이터 URL로 읽어 이미지 미리보기
    });
  }
  // 이미지 확대 보기 팝업 열기
  function openPopup(imageSrc) {
    const popup = document.getElementById('image-popup');
    const popupImage = document.getElementById('popup-image');
    popup.style.display = 'flex';
    popupImage.src = imageSrc;
  }
  // 이미지 확대 보기 팝업 닫기
  function closePopup() {
    const popup = document.getElementById('image-popup');
    popup.style.display = 'none';
  }
</script>
</body>
</html>