w01/emotion/urls.py
from django.urls import path,include
from . import views

app_name = "emotion"
urlpatterns = [
    path('main/', views.main, name="main"),
    path('main_data1/', views.main_data1, name="main_data1"),
    path('main_data2/', views.main_data2, name="main_data2"),
    path('main_data4/', views.main_data4, name="main_data4"),
    path('main_data5/', views.main_data5, name="main_data5"),
    path('report/', views.report, name="report"),
    path("run-ai/", views.run_ai_process, name="run_ai_process"),
    path('save_diaries_to_txt/', views.save_diaries_to_txt, name='save_diaries_to_txt'),
]

w01/w01/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin1/', include('admin1.urls')),
    path('loginpage/', include('loginpage.urls')),
    path('customer/', include('customer.urls')),
    path('emotion/', include('emotion.urls')),
    path('', include('home.urls')),
    path('main/', include('home.urls')),
    path('diary/', include('diary.urls')),
    path('mypage/', include('mypage.urls')),
    path('comment/', include('comment.urls')),
    path('calendar1/', include('calendar1.urls')),
    path('family1/', include('family1.urls')),
]


# settings.py 안에
# MEDIA_URL = 'media/' 로 들어오면
# MEDIA_ROOT = os.path.join(BASE_DIR,'media') 에서 찾아라
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin1/', include('admin1.urls')),
    path('loginpage/', include('loginpage.urls')),
    path('customer/', include('customer.urls')),
    path('emotion/', include('emotion.urls')),
    path('', include('home.urls')),
    path('main/', include('home.urls')),
    path('diary/', include('diary.urls')),
    path('mypage/', include('mypage.urls')),
    path('comment/', include('comment.urls')),
    path('calendar1/', include('calendar1.urls')),
    path('family1/', include('family1.urls')),
]


# settings.py 안에
# MEDIA_URL = 'media/' 로 들어오면
# MEDIA_ROOT = os.path.join(BASE_DIR,'media') 에서 찾아라
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

w01/emotion/models.py
from django.db import models
from loginpage.models import Member

from datetime import date
class EmotionScore(models.Model):
  member = models.ForeignKey(Member,on_delete=models.DO_NOTHING, null=True)
  # diaryNo = models.ForeignKey(일기내용 클래스)
  diaryNo = models.IntegerField(default=0)
  diarydate = models.DateField(default=date.today)
  emotionscore = models.IntegerField(default=0)

  def __str__(self):
    return f"{self.member}, {self.emotionscore}"

w01/emotion/views.py
from django.shortcuts import render
from django.http import JsonResponse
from datetime import datetime, timedelta
from django.db.models import Sum, Count, F, Q
from django.db.models.functions import Extract, TruncDate
from math import ceil
from calendar import monthrange
from loginpage.models import Member
from diary.models import Content
from emotion.models import EmotionScore

# AI PYTHON
import os
import base64
from vertexai.generative_models import GenerativeModel, Part, SafetySetting
import vertexai
from django.conf import settings

def save_content_to_txt():
    # Content 모델에서 모든 게시글 가져오기
    contents = Content.objects.all()
    # 'emotion/gemini' 폴더가 존재하는지 확인하고, 없으면 생성
    save_dir = os.path.join(settings.BASE_DIR, 'emotion', 'gemini')
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
    for i, content in enumerate(contents, start=1):
        # 'd숫자.txt' 파일 이름 지정
        file_name = f"d{i}.txt"
        file_path = os.path.join(save_dir, file_name)
        # ccontent와 cdate 가져오기
        ccontent = content.ccontent
        cdate = content.cdate
        # 텍스트 파일로 저장
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(f"{cdate.strftime('%Y-%m-%d %H:%M:%S')}\n\n")  # cdate를 첫 번째 줄에 작성
            f.write(f"{ccontent}\n")  # ccontent를 두 번째 줄에 작성
        print(f"{file_name} 저장 완료.")
        
def save_diaries_to_txt(request):
    save_content_to_txt()  # 게시글을 텍스트 파일로 저장하는 함수 호출
    return render(request, 'report.html')  # 알림 페이지로 리디렉션

# AI 작업을 위한 별도 함수 정의
def generate_for_multiple_files(mbti):
    model = GenerativeModel("gemini-1.5-flash-002")
    for i in range(1, 8):  # 처리할 파일 범위
        input_file_path = f"emotion/gemini/d{i}.txt"
        # output_file_path = f"emotion/gemini/r{i}.txt"
        # 현재 날짜를 파일 이름에 추가 (예: r2024-12-16.txt)
        output_file_path = f"emotion/gemini/r{i}.txt"
        
        try:
            with open(input_file_path, "r", encoding="utf-8") as file:
                file_content = file.read()
        except FileNotFoundError:
            continue

        # 유저 MBTI
        # MBTI = "ENTJ"
        
        combined_content = f"{file_content}\\n\\nMBTI: {mbti}"
        encoded_content = base64.b64encode(combined_content.encode("utf-8")).decode("utf-8")
        document = Part.from_data(mime_type="text/plain", data=encoded_content)
        
        text1 = """오늘 느낀 감정의 정리: Identify the overall sentiment of the review (e.g., positive, negative, or neutral).

        설명: Provide a detailed explanation and analysis for the identified sentiment, written in Korean. Make it sound like a psychologist's analysis. Do not write the explanation about MBTI and LBTI in here, write them
        in the MBTI/LBTI section.

        MBTI/LBTI AI 예측: The explanation must include references to the content of the review while retaining the words \"MBTI\" and \"LBTI\" in English. There should be no English words in the explanation.
        Predict the user's likely MBTI and LBTI types based on the review content. These predictions should be made confidently and articulated like a psychologist's analysis. Do not include statements like \"it is difficult to predict\" or \"requires more information.\"
        There's going to be a MBTI provided in the review from the user which is what they got for their MBTI prediction from the MBTI Test. 
        Compare them with the user's MBTI. If the content based "predicted by AI" MBTI is somewhat different with the user's MBTI, quote which part is different.
        It gives the user more interest if the MBTI is different say which MBTI suits the user in the journal.(very important)

        감정 점수: Calculate and present the percentages on the level of joy(기쁨의 정도), anxiety and stress(불안감과 스트레스), social satisfaction(사회적 만족감), achievement and self-esteem(성취와 자존감), and physical/mental well-being(신체적/정신적 웰빙).
        Ensure each emotion's total equals 100% and based on the scores, include the score of happiness(행복도 점수). Do not change the name. 행복도 점수는 100점 만점. 무조건.
        When scoring the happiness be very critical consider on the MBTI understand how this person will actually be happy or not. Do not say them directly but show them in the score. 

        동기부여 메세지: Conclude with an uplifting quote to motivate the user and encourage them to keep writing journals for further updates. No English. Write down a wise saying.

        The output should begin with \"스마트 AI 감정 분석 진단\" and be written in an engaging, detailed manner for better understanding and interest. Maintain a clear structure and avoid unnecessary complexity.
        Organize the analysis results with a specific date format (YYYY-MM-DD-Day) at the start of the analisis after the title.
        Lastly this report will be saved as .txt file so divide the sentences to look pretty and readable also section's name should be equal everytime.
        DO NOT CHANGE THE SECTIONS.
        """
        
        generation_config = {"max_output_tokens": 3333, "temperature": 1, "top_p": 0.95}
        safety_settings = [
            SafetySetting(category=SafetySetting.HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold=SafetySetting.HarmBlockThreshold.OFF)
        ]
        
        responses = model.generate_content([document, text1], generation_config=generation_config, safety_settings=safety_settings, stream=True)
        output_content = "".join(response.text for response in responses)
        
        with open(output_file_path, "w", encoding="utf-8") as output_file:
            output_file.write(output_content)

# AI 작업을 위한 뷰 함수
def run_ai_process(request):
    if request.method == 'GET':
        # 사용자가 선택한 MBTI 값 가져오기
        selected_mbti = request.GET.get('mbti')
    
    # Google Vertex AI 설정
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = ""
    vertexai.init(project="alert-condition-443702-g2", location="us-central1")
    
    # AI 작업 실행
    generate_for_multiple_files(selected_mbti)

    # # 생성된 파일 내용 반환 (예: r1.txt)
    # output_file_path = "emotion/gemini/r1.txt"
    # if os.path.exists(output_file_path):
    #     with open(output_file_path, "r", encoding="utf-8") as f:
    #         content = f.read()
    #     return render(request, 'report.html', {'content': content})  # 템플릿에 데이터 전달
    # else:
    #     return render(request, 'report.html', {'error': '파일이 생성되지 않았습니다.'})  # 오류 처리

    # 생성된 파일들 읽어서 내용 이어서 출력
    output_content = ""
    
    for i in range(1, 8):  # r1.txt, r2.txt, r3.txt 순으로 파일 읽기
        # output_file_path = f"emotion/gemini/r{i}.txt"
        current_date = datetime.now().strftime("%Y-%m-%d")  # 파일 이름의 날짜 부분
        output_file_path = f"emotion/gemini/r{current_date}_{i}.txt"
        
        if os.path.exists(output_file_path):
            with open(output_file_path, "r", encoding="utf-8") as f:
                file_content = f.read()
                # output_content += f"--- 일기{i}.txt ---\n"  # 각 파일 구분 라인
                output_content += f"--- {current_date} 일기 (마지막으로 수정된 날 기준입니다.) ---\n"  # 각 파일 구분 라인
                output_content += file_content + "\n\n"  # 파일 내용 추가
        else:
            output_content += f"이번 주 일기{i} 생성되지 않았습니다.\n\n"  # 파일 없을 때 메시지 추가
            
            
    # 정상적으로 결과가 있으면 render를 호출하여 페이지 반환
    return render(request, 'report.html', {'content': output_content})

def report(request):
    return render(request, 'report.html')

def main(request):
  # 프로필 가져오기 
  id = request.session['session_id']
  mem = Member.objects.filter(id = id )
  name = mem[0].name
  # 날짜 가져오기
  current_date = datetime.today()
  year = current_date.year
  month = current_date.month

  # 주 수 가져오기
  # 현재 날짜가 속한 달의 첫 번째 날 (12월 1일)
  first_day_of_month = current_date.replace(day=1)
  # 오늘 날짜와 첫 번째 날 사이의 일수를 계산
  days_into_month = (current_date - first_day_of_month).days

  # 주 수 계산
  week_number = (days_into_month // 7) + 1

  ## 일기 몇개 썼는지 가져오기
  # main_data5에서 데이터 가져오기
  data, total_value, total_value2 = get_data5(id)
    
  context = {
      'mem_info':mem[0], 
      'year':year, 
      'month':month, 
      'week':week_number, 
      'name':name[1:],
      'total_value':total_value,
      'total_value2':total_value2
      }
  return render(request, 'e_main.html', context)

def main_data1(request):
    # 현재 날짜 기준으로 year, month 구하기
    current_date = datetime.today()
    year = current_date.year
    month = current_date.month

    # 프로필 가져오기
    member = Member.objects.get(id=request.session['session_id'])
    scores = EmotionScore.objects.filter(member=member, diarydate__year=year, diarydate__month=month)

    # 다음 달 계산 및 현재 월의 마지막 날짜 계산
    if month == 12:  # 12월일 경우
        next_month = 1
        next_year = year + 1
    else:
        next_month = month + 1
        next_year = year

    days_in_month = (datetime(next_year, next_month, 1) - timedelta(days=1)).day

    # 총 주 계산
    total_weeks = (days_in_month - 1) // 7 + 1
    week_data = {week: {"total_value": 0, "count": 0} for week in range(1, total_weeks + 1)}

    # 그룹화 데이터 가져오기
    grouped_data = (
        scores.annotate(
            day_of_month=Extract('diarydate', 'day'),  # 일(day)만 추출
        )
        .values('day_of_month')  # 일(day) 기준으로 그룹화
        .annotate(
            total_value=Sum('emotionscore'),  # 합계 계산
            count=Count('emotionscore')  # 개수 계산
        )
        .order_by('day_of_month')  # 날짜 순으로 정렬
    )

    # 주별 데이터 계산
    for item in grouped_data:
        week_of_month = (item['day_of_month'] - 1) // 7 + 1
        week_data[week_of_month]['total_value'] += item['total_value']
        week_data[week_of_month]['count'] += item['count']

    # 주별 평균값 계산
    data = []
    for week, values in week_data.items():
        average_value = round(values['total_value'] / values['count'], 2) if values['count'] > 0 else 0
        data.append({"name": f"{week}주", "value": average_value})

    print("Final Data:", data)  # 디버깅용
    return JsonResponse(data, safe=False)

def main_data2(request):
    try:
        # 현재 날짜 기준으로 year, month, weekday(오늘 요일) 구하기

w01/emotion/templates/report.html
<<<<<<< HEAD
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/home/main.css'%}">
	<link rel="stylesheet" href="{% static 'css/emotion/report.css'%}">

	<link rel="stylesheet" as="style" crossorigin
		href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css" />
	
	<script src="http://code.jquery.com/jquery-latest.min.js"></script>
	<title>감정 돌아보기</title>
	<style>
		pre {
			white-space: pre-wrap; /* 자동 줄 바꿈 */
			word-wrap: break-word; /* 긴 단어는 줄바꿈 */
			background-color: #f4f4f4; /* 배경색 */
			padding: 20px;
			border-radius: 5px;
		}
	</style>
	
	<script>
		$(function () {
			// GNB 클릭
			$('#menu ul li').on('click', function () {
				$('#menu ul li').removeClass('active');
				$(this).addClass('active');
			});
		});
	</script>
</head>

<body>
	<!-- 최상단 메뉴 -->
	<div id="top_nav">
		<h1><a href="/main/index/"></a></h1>
		<ul class="top_menu">
			<li><a href="#"><img src="/static/images/home/search_icon.png" alt=""></a></li>
			<li><a href="#"><img src="/static/images/home/bell_off_icon.png" alt=""></a></li>
			<li><a href="#">마이페이지</a></li>
		</ul>

	</div>

	<!-- 좌측 gnb -->
	<div id="gnb">

		<!-- 프로필 -->
		<div id="user_profile">
			<div id="pimg">
				<img src="/static/images/home/default_profile.png" alt="">
			</div>
			<p id="uName">김용준</p>
			<p id="uEmail">kyjoon0105@gmail.com</p>
		</div>

		<!-- Nav -->
		<nav id="menu">
			<ul>
				<a href="#">
					<li class="menu_item">우리 가족 이야기</li>
				</a>
				<a href="#">
					<li class="menu_item">다이어리</li>
				</a>
				<a href="/emotion/main/">
					<li class="menu_item active">감정 돌아보기</li>
				</a>
				<a href="#">
					<li class="menu_item">우리가족</li>
				</a>
				<a href="#">
					<li class="menu_item">캘린더</li>
				</a>
				<a href="#">
					<li class="menu_item">알려드려요</li>
				</a>
			</ul>
		</nav>

		<!-- logout -->
		<div id="logout">
			<a href="#"><span>로그아웃</span></a>
		</div>

	</div>

	<!-- container -->
	<div id="container_report">
		<span id="main_title">내 감정 돌아보기</span>
		<div id="sub_title">
			<h1>AI 감정 분석 리포트</h1>
			<h3>용준 님의 최근 일주일의 기록을 바탕으로 AI가 분석한 감정 리포트를 보여드릴게요.</h3>
			<h4><strong>AI 감정 분석 리포트</strong> 란?</h4>
			<h5>사용자의 기록 내용에서 감정의 점수를 매겨 기록 속의 MBTI와 LBTI를 분석해요. 그 후 사용자의 실제 MBTI에 기반하여<br>
				환경과 맥락에 따라 사용자의 MBTI가 일기속 내용을 바탕으로 AI가 예측하는 MBTI와 비교해 보다 더 깊은 본인 통찰력을 제공해 드려요.<br>
				AI 분석은 재미로 가볍게 참고하는 정도로 보시는 걸 추천드려요! 😊</h5>
		</div>

		<div id="report_container">
			<div id="mbtitle">
				<span>나의 MBTI 입력하고 AI 감정 분석하기</span>
			</div>
			<form method="GET" action="{% url 'emotion:run_ai_process' %}">
				<div id="select_mbti">
					<select class="mbti" name="mbti">
						<option value="select">선택</option>
						<option value="ISTJ">ISTJ</option>
						<option value="ISFJ">ISFJ</option>
						<option value="INFJ">INFJ</option>
						<option value="INTJ">INTJ</option>
						<option value="ISTP">ISTP</option>
						<option value="ISFP">ISFP</option>
						<option value="INFP">INFP</option>
						<option value="INTP">INTP</option>
						<option value="ESTP">ESTP</option>
						<option value="ESFP">ESFP</option>
						<option value="ENFP">ENFP</option>
						<option value="ENTP">ENTP</option>
						<option value="ESTJ">ESTJ</option>
						<option value="ESFJ">ESFJ</option>
						<option value="ENFJ">ENFJ</option>
						<option value="ENTJ">ENTJ</option>
					</select>
						<button type="submit" id="aiBtn">분석시작</button>
					</form>
				</div>
		</div>

		<div id="report_main">
			<span>AI 감정 분석 리포트</span>
			<hr color="#D9D9D9">
			<div id="report_txt">
				{% if content %}
					<div>
							<h2>분석 결과:</h2><br>
							<pre>{{ content }}</pre>  <!-- 분석된 AI 결과 출력 -->
					</div>
				{% elif error %}
					<div style="color: red;">
							<p>{{ error }}</p>  <!-- 오류 메시지 출력 -->
					</div>
				{% else %}
				  <h2>💥주의💥</h2>
					<p>AI 분석이 아직 실행되지 않았습니다. MBTI를 선택 후 분석 시작 버튼을 <strong>한 번만</strong> 눌러주세요.<br> <strong>처리 시간이 조금 걸릴 수도 있습니다. 조금만 기다려 주세요!</strong><br>
						❗새로고침을 하거나 페이지를 나가면 분석 결과가 초기화되어 결과가 바뀔 수도 있습니다.
						<br><strong>( 이후 이전 결과는 되돌리기 쉽지 않습니다. 💦)</strong></p>
				{% endif %}

			</div>
		</div>
		<div id="bottom">
			<span>상기 리포트 AI가 작성한 것으로 일상생활에서의 참고용 정도로만 봐주세요.</span>
			<button type="button">다운로드</button>
		</div>
	</div>

	<!-- footer -->

	<script >
		// 페이지 로딩 시 AJAX 요청을 보내서 데이터 받기
		$.ajax({
			url: "/emotion/report/",  // '/emotion/report/' 경로로 요청
			type: "GET",
			success: function(response) {
					if (response.content) {
							// 응답받은 content 데이터 표시
							$('#result').text(response.content);
					} else {
							$('#result').text('결과를 가져오려면 분석 시작 버튼을 클릭해주세요.');
					}
			},
			error: function() {
					$('#result').text('서버 오류가 발생했습니다.');
			}
	});

	</script>


</body>

=======
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/home/main.css'%}">
	<link rel="stylesheet" href="{% static 'css/emotion/report.css'%}">

	<link rel="stylesheet" as="style" crossorigin
		href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css" />
	
	<script src="http://code.jquery.com/jquery-latest.min.js"></script>
	<title>감정 돌아보기</title>
	<style>
		pre {
			white-space: pre-wrap; /* 자동 줄 바꿈 */
			word-wrap: break-word; /* 긴 단어는 줄바꿈 */
			background-color: #f4f4f4; /* 배경색 */
			padding: 20px;
			border-radius: 5px;
		}
	</style>
	
	<script>
		$(function () {
			// GNB 클릭
			$('#menu ul li').on('click', function () {
				$('#menu ul li').removeClass('active');
				$(this).addClass('active');
			});
		});
	</script>
</head>

<body>
	<!-- 최상단 메뉴 -->
	<div id="top_nav">
		<h1><a href="/main/index/"></a></h1>
		<ul class="top_menu">
			<li><a href="#"><img src="/static/images/home/search_icon.png" alt=""></a></li>
			<li><a href="#"><img src="/static/images/home/bell_off_icon.png" alt=""></a></li>
			<li><a href="#">마이페이지</a></li>
		</ul>

	</div>

	<!-- 좌측 gnb -->
	<div id="gnb">

		<!-- 프로필 -->
		<div id="user_profile">
			<div id="pimg">
				<img src="/static/images/home/default_profile.png" alt="">
			</div>
			<p id="uName">김용준</p>
			<p id="uEmail">kyjoon0105@gmail.com</p>
		</div>

		<!-- Nav -->
		<nav id="menu">
			<ul>
				<a href="#">
					<li class="menu_item">우리 가족 이야기</li>
				</a>
				<a href="#">
					<li class="menu_item">다이어리</li>
				</a>
				<a href="/emotion/main/">
					<li class="menu_item active">감정 돌아보기</li>
				</a>
				<a href="#">
					<li class="menu_item">우리가족</li>
				</a>
				<a href="#">
					<li class="menu_item">캘린더</li>
				</a>
				<a href="#">
					<li class="menu_item">알려드려요</li>
				</a>
			</ul>
		</nav>

		<!-- logout -->
		<div id="logout">
			<a href="#"><span>로그아웃</span></a>
		</div>

	</div>

	<!-- container -->
	<div id="container_report">
		<span id="main_title">내 감정 돌아보기</span>
		<div id="sub_title">
			<h1>AI 감정 분석 리포트</h1>
			<h3>용준 님의 최근 일주일의 기록을 바탕으로 AI가 분석한 감정 리포트를 보여드릴게요.</h3>
			<h4><strong>AI 감정 분석 리포트</strong> 란?</h4>
			<h5>사용자의 기록 내용에서 감정의 점수를 매겨 기록 속의 MBTI와 LBTI를 분석해요. 그 후 사용자의 실제 MBTI에 기반하여<br>
				환경과 맥락에 따라 사용자의 MBTI가 일기속 내용을 바탕으로 AI가 예측하는 MBTI와 비교해 보다 더 깊은 본인 통찰력을 제공해 드려요.<br>
				AI 분석은 재미로 가볍게 참고하는 정도로 보시는 걸 추천드려요! 😊</h5>
		</div>

		<div id="report_container">
			<div id="mbtitle">
				<span>나의 MBTI 입력하고 AI 감정 분석하기</span>
			</div>
			<form method="GET" action="{% url 'emotion:run_ai_process' %}">
				<div id="select_mbti">
					<select class="mbti" name="mbti">
						<option value="select">선택</option>
						<option value="ISTJ">ISTJ</option>
						<option value="ISFJ">ISFJ</option>
						<option value="INFJ">INFJ</option>
						<option value="INTJ">INTJ</option>
						<option value="ISTP">ISTP</option>
						<option value="ISFP">ISFP</option>
						<option value="INFP">INFP</option>
						<option value="INTP">INTP</option>
						<option value="ESTP">ESTP</option>
						<option value="ESFP">ESFP</option>
						<option value="ENFP">ENFP</option>
						<option value="ENTP">ENTP</option>
						<option value="ESTJ">ESTJ</option>
						<option value="ESFJ">ESFJ</option>
						<option value="ENFJ">ENFJ</option>
						<option value="ENTJ">ENTJ</option>
					</select>
						<button type="submit" id="aiBtn">분석시작</button>
					</form>
				</div>
		</div>

		<div id="report_main">
			<span>AI 감정 분석 리포트</span>
			<hr color="#D9D9D9">
			<div id="report_txt">
				{% if content %}
					<div>
							<h2>분석 결과:</h2><br>
							<pre>{{ content }}</pre>  <!-- 분석된 AI 결과 출력 -->
					</div>
				{% elif error %}
					<div style="color: red;">
							<p>{{ error }}</p>  <!-- 오류 메시지 출력 -->
					</div>
				{% else %}
				  <h2>💥주의💥</h2>
					<p>AI 분석이 아직 실행되지 않았습니다. MBTI를 선택 후 분석 시작 버튼을 <strong>한 번만</strong> 눌러주세요.<br> <strong>처리 시간이 조금 걸릴 수도 있습니다. 조금만 기다려 주세요!</strong><br>
						❗새로고침을 하거나 페이지를 나가면 분석 결과가 초기화되어 결과가 바뀔 수도 있습니다.
						<br><strong>( 이후 이전 결과는 되돌리기 쉽지 않습니다. 💦)</strong></p>
				{% endif %}

			</div>
		</div>
		<div id="bottom">
			<span>상기 리포트 AI가 작성한 것으로 일상생활에서의 참고용 정도로만 봐주세요.</span>
			<button type="button">다운로드</button>
		</div>
	</div>

	<!-- footer -->

	<script >
		// 페이지 로딩 시 AJAX 요청을 보내서 데이터 받기
		$.ajax({
			url: "/emotion/report/",  // '/emotion/report/' 경로로 요청
			type: "GET",
			success: function(response) {
					if (response.content) {
							// 응답받은 content 데이터 표시
							$('#result').text(response.content);
					} else {
							$('#result').text('결과를 가져오려면 분석 시작 버튼을 클릭해주세요.');
					}
			},
			error: function() {
					$('#result').text('서버 오류가 발생했습니다.');
			}
	});

	</script>


</body>

>>>>>>> 0224d1acfb885c3d59df586193b7eb004165ba6c
</html>